version: '3.3'  # 可以根據需要選擇不同的版本

services:
  l4a_etl_sup:
    image: at_image  # 映像名稱
    container_name: l4a_etl_sup  # 容器名稱
    restart: always  # 自動重啟策略
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 掛載 /etc/localtime
      - /home/ivan/Program:/app
    devices:
      - /dev/fuse  # 使用 FUSE 設備
    cap_add:
      - SYS_ADMIN  # 增加 SYS_ADMIN 權限
    privileged: true  # 以特權模式運行
    working_dir: /app/AT_CODE_SUP  # 設定工作目錄到 AT_CODE
    command: python l4a_etl.py  # 執行的命令

  l6b_fs_eb16c_etl_sup:
    image: at_image  # 映像名稱
    container_name: l6b_fs_eb16c_etl_sup  # 容器名稱
    restart: always  # 自動重啟策略
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 掛載 /etc/localtime
      - /home/ivan/Program:/app
    devices:
      - /dev/fuse  # 使用 FUSE 設備
    cap_add:
      - SYS_ADMIN  # 增加 SYS_ADMIN 權限
    privileged: true  # 以特權模式運行
    working_dir: /app/AT_CODE_SUP  # 設定工作目錄到 AT_CODE
    command: python l6b_fs_eb16c_etl.py  # 執行的命令

  l6b_fs_eb17c_etl_sup:
    image: at_image  # 映像名稱
    container_name: l6b_fs_eb17c_etl_sup  # 容器名稱
    restart: always  # 自動重啟策略
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 掛載 /etc/localtime
      - /home/ivan/Program:/app
    devices:
      - /dev/fuse  # 使用 FUSE 設備
    cap_add:
      - SYS_ADMIN  # 增加 SYS_ADMIN 權限
    privileged: true  # 以特權模式運行
    working_dir: /app/AT_CODE_SUP  # 設定工作目錄到 AT_CODE
    command: python l6b_fs_eb17c_etl.py  # 執行的命令

  l6b_sw_at2_etl_sup:
    image: at_image  # 映像名稱
    container_name: l6b_sw_at2_etl_sup  # 容器名稱
    restart: always  # 自動重啟策略
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 掛載 /etc/localtime
      - /home/ivan/Program:/app
    devices:
      - /dev/fuse  # 使用 FUSE 設備
    cap_add:
      - SYS_ADMIN  # 增加 SYS_ADMIN 權限
    privileged: true  # 以特權模式運行
    working_dir: /app/AT_CODE_SUP  # 設定工作目錄到 AT_CODE
    command: python l6b_sw_at2_etl.py  # 執行的命令

  l6b_sw_tc01_etl_sup:
    image: at_image  # 映像名稱
    container_name: l6b_sw_tc01_etl_sup  # 容器名稱
    restart: always  # 自動重啟策略
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 掛載 /etc/localtime
      - /home/ivan/Program:/app
    devices:
      - /dev/fuse  # 使用 FUSE 設備
    cap_add:
      - SYS_ADMIN  # 增加 SYS_ADMIN 權限
    privileged: true  # 以特權模式運行
    working_dir: /app/AT_CODE_SUP  # 設定工作目錄到 AT_CODE
    command: python l6b_sw_tc01_etl.py  # 執行的命令

  l6b_sw_tc02_etl_sup:
    image: at_image  # 映像名稱
    container_name: l6b_sw_tc02_etl_sup  # 容器名稱
    restart: always  # 自動重啟策略
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 掛載 /etc/localtime
      - /home/ivan/Program:/app
    devices:
      - /dev/fuse  # 使用 FUSE 設備
    cap_add:
      - SYS_ADMIN  # 增加 SYS_ADMIN 權限
    privileged: true  # 以特權模式運行
    working_dir: /app/AT_CODE_SUP  # 設定工作目錄到 AT_CODE
    command: python l6b_sw_tc02_etl.py  # 執行的命令
